# Generated by Django 3.2.3 on 2021-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_updated',),
            },
        ),
    ]
