# Generated by Django 3.2.3 on 2021-05-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20210515_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('-date_updated',)},
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
