# Generated by Django 3.2.3 on 2021-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_auto_20210517_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
